# //oemcomma    ,
# //oemperiod   .
# //oem2        /
# //oem1        ;
# //oem7        '
# //oem4        [
# //oem6        ]
# //oem5        \
# //oemminus    -
# //oemplus     =

caps: # tigger with CapsLock. Used in 1 (normal) and 2 (insert) state
  e: esc
  h: backspace
  y: ctrl+backspace
  l: del
  d: del
  j: enter
  r: enter
  t: tab
  g: shift+tab
  c: shift+f10 # Shift + F10 (context menu)
  v: ctrl+shift+v # Ctrl + Shift + v (paste without formatting)
  m: ctrl+tab
  comma: ctrl+shift+tab


common: # without first step
  h: left         # left arrow
  j: down         # down arrow
  k: up           # up arrow
  l: right        # right arrow
  n: home
  m: page down
  comma: page up
  period: end
  y: ctrl+left        # CTRL + left arrow (go by word)
  o: ctrl+right       # CTRL + right arrow (go by word)
  z: ctrl+z             # CTRL + z
  x: ctrl+x             # CTRL + x
  c: ctrl+c             # CTRL + c
  v: ctrl+v             # CTRL + v

f: # first step f
  # F keys
  d1: f1
  d2: f2
  d3: f3
  d4: f4
  d5: f5
  d6: f6
  q: f7
  w: f8
  e: f9
  r: f10
  t: f11
  f: f12
  # other shortcuts
  s: shift+esc # shift ESC

i: # first step i
  j: end, enter # Insert line below
  k: up, end, enter # Insert line above


d: # first step d
  z: ctrl+f7,ctrl+f8 # EvernoteFocusListTrick

q:
  d1: alt+shift+f1
  d2: alt+shift+f2
  d3: alt+shift+f3
  d4: alt+shift+f4
  d5: alt+shift+f5
  d6: alt+shift+f6
  d7: alt+shift+f7
  d8: alt+shift+f8
  d9: alt+shift+f9
  d0: alt+shift+f10
  minus: alt+shift+-
  plus: alt+shift+=
  q: alt+shift+q
  w: alt+shift+w
  e: alt+shift+e
  r: alt+shift+r
  t: alt+shift+t
  y: alt+shift+y
  u: alt+shift+u
  i: alt+shift+i
  o: alt+shift+o
  p: alt+shift+p
  a: alt+shift+a
  s: alt+shift+s
  d: alt+shift+d
  f: alt+shift+f
  g: alt+shift+g
  h: alt+shift+h
  j: alt+shift+j
  k: alt+shift+k
  l: alt+shift+l
  oem1: alt+shift+;
  oem7: alt+shift+'
  z: alt+shift+z
  x: alt+shift+x
  c: alt+shift+c
  v: alt+shift+v
  b: alt+shift+b
  n: alt+shift+n
  m: alt+shift+m
  comma: alt+shift+,
  period: alt+shift+.
  oem2: alt+shift+/
  openbrackets: alt+shift+[
  oem6: alt+shift+]
  oem5: alt+shift+\



# //q
# qd1
# qd2
# qd3
# qd4
# qd5
# qd6
# qd7
# qd8
# qd9
# qd0
# qoemminus        alt+shift+-
# qoemplus         alt+shift+=
# qq               alt+shift+q
# qw               alt+shift+w
# qe               alt+shift+e
# qr               alt+shift+r
# qt               alt+shift+t
# qy               alt+shift+y
# qu               alt+shift+u
# qi               alt+shift+i
# qo               alt+shift+o
# qp               alt+shift+p
# qa               alt+shift+a
# qs               alt+shift+s
# qd               alt+shift+d
# qf               alt+shift+f
# qg               alt+shift+g
# qh               alt+shift+h
# qj               alt+shift+j
# qk               alt+shift+k
# ql               alt+shift+l
# qoem1            alt+shift+;
# qoem7            alt+shift+'
# qz               alt+shift+z
# qx               alt+shift+x
# qc               alt+shift+c
# qv               alt+shift+v
# qb               alt+shift+b
# qn               alt+shift+n
# qm               alt+shift+m
# qoemcomma        alt+shift+,
# qoemperiod       alt+shift+.
# qoem2            alt+shift+/
# qoemopenbrackets alt+shift+[
# qoem6            alt+shift+]
# qoem5            alt+shift+\
#
#
# //w
# wd1              alt+f1
# wd2              alt+f2
# wd3              alt+f3
# wd4              alt+f4
# wd5              alt+f5
# wd6              alt+f6
# wd7              alt+f7
# wd8              alt+f8
# wd9              alt+f9
# wd0              alt+f10
# woemminus        alt+-
# woemplus         alt+=
# wq               alt+q
# ww               alt+w
# we               alt+e
# wr               alt+r
# wt               alt+t
# wy               alt+y
# wu               alt+u
# wi               alt+i
# wo               alt+o
# wp               alt+p
# wa               alt+a
# ws               alt+s
# wd               alt+d
# wf               alt+f
# wg               alt+g
# wh               alt+h
# wj               alt+j
# wk               alt+k
# wl               alt+l
# woem1            alt+;
# woem7            alt+'
# wz               alt+z
# wx               alt+x
# wc               alt+c
# wv               alt+v
# wb               alt+b
# wn               alt+n
# wm               alt+m
# woemcomma        alt+,
# woemperiod       alt+.
# woem2            alt+/
# woemopenbrackets alt+[
# woem6            alt+]
# woem5            alt+\
#
# //e
# ed1              ctrl+f1
# ed2              ctrl+f2
# ed3              ctrl+f3
# ed4              ctrl+f4
# ed5              ctrl+f5
# ed6              ctrl+f6
# ed7              ctrl+f7
# ed8              ctrl+f8
# ed9              ctrl+f9
# ed0              ctrl+f10
# eoemminus        ctrl+-
# eoemplus         ctrl+=
# eq               ctrl+q
# ew               ctrl+w
# ee               ctrl+e
# er               ctrl+r
# et               ctrl+t
# ey               ctrl+y
# eu               ctrl+u
# ei               ctrl+i
# eo               ctrl+o
# ep               ctrl+p
# ea               ctrl+a
# es               ctrl+s
# ed               ctrl+d
# ef               ctrl+f
# eg               ctrl+g
# eh               ctrl+h
# ej               ctrl+j
# ek               ctrl+k
# el               ctrl+l
# eoem1            ctrl+;
# eoem7            ctrl+'
# eb               ctrl+b
# en               ctrl+n
# em               ctrl+m
# eoemcomma        ctrl+,
# eoemperiod       ctrl+.
# eoem2            ctrl+/
# eoemopenbrackets ctrl+[
# eoem6            ctrl+]
# eoem5            ctrl+\
#
# //r
# rd1              shift+f1
# rd2              shift+f2
# rd3              shift+f3
# rd4              shift+f4
# rd5              shift+f5
# rd6              shift+f6
# rd7              shift+f7
# rd8              shift+f8
# rd9              shift+f9
# rd0              shift+f10
# roemminus        shift+-
# roemplus         shift+=
# rq               shift+q
# rw               shift+w
# re               shift+e
# rr               shift+r
# rt               shift+t
# ry               shift+y
# ru               shift+u
# ri               shift+i
# ro               shift+o
# rp               shift+p
# ra               shift+a
# rs               shift+s
# rd               shift+d
# rf               shift+f
# rg               shift+g
# rh               shift+h
# rj               shift+j
# rk               shift+k
# rl               shift+l
# roem1            shift+;
# roem7            shift+'
# rz               shift+z
# rx               shift+x
# rc               shift+c
# rv               shift+v
# rb               shift+b
# rn               shift+n
# rm               shift+m
# roemcomma        shift+,
# roemperiod       shift+.
# roem2            shift+/
# roemopenbrackets shift+[
# roem6            shift+]
# roem5            shift+\
#
# //t
# td1              ctrl+shift+f1
# td2              ctrl+shift+f2
# td3              ctrl+shift+f3
# td4              ctrl+shift+f4
# td5              ctrl+shift+f5
# td6              ctrl+shift+f6
# td7              ctrl+shift+f7
# td8              ctrl+shift+f8
# td9              ctrl+shift+f9
# td0              ctrl+shift+f10
# toemminus        ctrl+shift+-
# toemplus         ctrl+shift+=
# tq               ctrl+shift+q
# tw               ctrl+shift+w
# te               ctrl+shift+e
# tr               ctrl+shift+r
# tt               ctrl+shift+t
# ty               ctrl+shift+y
# tu               ctrl+shift+u
# ti               ctrl+shift+i
# to               ctrl+shift+o
# tp               ctrl+shift+p
# ta               ctrl+shift+a
# ts               ctrl+shift+s
# td               ctrl+shift+d
# tf               ctrl+shift+f
# tg               ctrl+shift+g
# th               ctrl+shift+h
# tj               ctrl+shift+j
# tk               ctrl+shift+k
# tl               ctrl+shift+l
# toem1            ctrl+shift+;
# toem7            ctrl+shift+'
# tz               ctrl+shift+z
# tx               ctrl+shift+x
# tc               ctrl+shift+c
# tv               ctrl+shift+v
# tb               ctrl+shift+b
# tn               ctrl+shift+n
# tm               ctrl+shift+m
# toemcomma        ctrl+shift+,
# toemperiod       ctrl+shift+.
# toem2            ctrl+shift+/
# toemopenbrackets ctrl+shift+[
# toem6            ctrl+shift+]
# toem5            ctrl+shift+\
#
# //g
# gd1              ctrl+alt+f1
# gd2              ctrl+alt+f2
# gd3              ctrl+alt+f3
# gd4              ctrl+alt+f4
# gd5              ctrl+alt+f5
# gd6              ctrl+alt+f6
# gd7              ctrl+alt+f7
# gd8              ctrl+alt+f8
# gd9              ctrl+alt+f9
# gd0              ctrl+alt+f10
# goemminus        ctrl+alt+-
# goemplus         ctrl+alt+=
# gq               ctrl+alt+q
# gw               ctrl+alt+w
# ge               ctrl+alt+e
# gr               ctrl+alt+r
# gt               ctrl+alt+t
# gy               ctrl+alt+y
# gu               ctrl+alt+u
# gi               ctrl+alt+i
# go               ctrl+alt+o
# gp               ctrl+alt+p
# ga               ctrl+alt+a
# gs               ctrl+alt+s
# gd               ctrl+alt+d
# gf               ctrl+alt+f
# gg               ctrl+alt+g
# gh               ctrl+alt+h
# gj               ctrl+alt+j
# gk               ctrl+alt+k
# gl               ctrl+alt+l
# goem1            ctrl+alt+;
# goem7            ctrl+alt+'
# gz               ctrl+alt+z
# gx               ctrl+alt+x
# gc               ctrl+alt+c
# gv               ctrl+alt+v
# gb               ctrl+alt+b
# gn               ctrl+alt+n
# gm               ctrl+alt+m
# goemcomma        ctrl+alt+,
# goemperiod       ctrl+alt+.
# goem2            ctrl+alt+/
# goemopenbrackets ctrl+alt+[
# goem6            ctrl+alt+]
# goem5            ctrl+alt+\
#
# b
# bd1              ctrl+alt+shift+f1
# bd2              ctrl+alt+shift+f2
# bd3              ctrl+alt+shift+f3
# bd4              ctrl+alt+shift+f4
# bd5              ctrl+alt+shift+f5
# bd6              ctrl+alt+shift+f6
# bd7              ctrl+alt+shift+f7
# bd8              ctrl+alt+shift+f8
# bd9              ctrl+alt+shift+f9
# bd0              ctrl+alt+shift+f10
# boemminus        ctrl+alt+shift+-
# boemplus         ctrl+alt+shift+=
# bq               ctrl+alt+shift+q
# bw               ctrl+alt+shift+w
# be               ctrl+alt+shift+e
# br               ctrl+alt+shift+r
# bt               ctrl+alt+shift+t
# by               ctrl+alt+shift+y
# bu               ctrl+alt+shift+u
# bi               ctrl+alt+shift+i
# bo               ctrl+alt+shift+o
# bp               ctrl+alt+shift+p
# ba               ctrl+alt+shift+a
# bs               ctrl+alt+shift+s
# bd               ctrl+alt+shift+d
# bf               ctrl+alt+shift+f
# bg               ctrl+alt+shift+g
# bh               ctrl+alt+shift+h
# bj               ctrl+alt+shift+j
# bk               ctrl+alt+shift+k
# bl               ctrl+alt+shift+l
# boem1            ctrl+alt+shift+;
# boem7            ctrl+alt+shift+'
# bz               ctrl+alt+shift+z
# bx               ctrl+alt+shift+x
# bc               ctrl+alt+shift+c
# bv               ctrl+alt+shift+v
# bb               ctrl+alt+shift+b
# bn               ctrl+alt+shift+n
# bm               ctrl+alt+shift+m
# boemcomma        ctrl+alt+shift+,
# boemperiod       ctrl+alt+shift+.
# boem2            ctrl+alt+shift+/
# boemopenbrackets ctrl+alt+shift+[
# boem6            ctrl+alt+shift+]
# boem5            ctrl+alt+shift+\
